// Lista curada de "Top Games" — pesquisada (best-sellers da Wikipedia +
// listas de "melhores jogos de SNES" de sites como Nintendo Life,
// GamesRadar e IGN) e cruzada com os slugs que realmente existem na
// biblioteca (ver ROMS.md pra como ela e' montada). So slugs presentes na
// pasta SNES/ entram aqui — nada e' referenciado sem existir.
//
// Nota: alguns titulos (Final Fantasy IV/V/VI, Super Mario RPG, Front
// Mission, Tales of Phantasia, Star Ocean, Bahamut Lagoon) so existem
// nesta colecao em japones (sem patch de traducao) — sao historicamente
// dos RPGs mais aclamados do SNES, mas o texto do jogo nao vai estar em
// portugues/ingles. Mantidos na lista por merito, com esse aviso aqui.
export const TOP_GAME_SLUGS = new Set([
  // Mais vendidos (best-sellers oficiais, Wikipedia)
  "snes-super-mario-world-usa",
  "snes-super-mario-all-stars-usa",
  "snes-donkey-kong-country-usa",
  "snes-super-mario-kart-usa",
  "snes-street-fighter-ii-the-world-warrior-usa",
  "snes-donkey-kong-country-2-diddy-s-kong-quest-usa-en-fr",
  "snes-legend-of-zelda-the-a-link-to-the-past-usa",
  "snes-super-mario-world-2-yoshi-s-island-usa",
  "snes-street-fighter-ii-turbo-hyper-fighting-usa",
  "snes-star-fox-usa",
  "snes-donkey-kong-country-3-dixie-kong-s-double-trouble-usa-en-fr",
  "snes-final-fantasy-vi-japan",
  "snes-killer-instinct-usa",
  "snes-f-zero-usa",
  "snes-chrono-trigger-usa",
  "snes-final-fantasy-v-japan",
  "snes-mario-paint-europe",
  "snes-super-mario-rpg-japan",
  "snes-pilotwings-usa",
  "snes-super-street-fighter-ii-the-new-challengers-usa",
  "snes-simcity-usa",
  "snes-secret-of-mana-usa",
  "snes-final-fantasy-iv-japan-rev-a",
  "snes-aladdin-usa",
  "snes-mortal-kombat-2-usa",
  "snes-final-fight-usa",
  "snes-kirby-super-star-usa",
  "snes-super-metroid-europe-en-fr-de",
  "snes-lion-king-the-usa",
  "snes-nba-jam-usa",
  "snes-mortal-kombat-3-usa",
  "snes-magical-quest-starring-mickey-mouse-the-usa",
  "snes-super-ghouls-n-ghosts-usa",
  "snes-final-fight-2-usa",
  "snes-tetris-2-usa",
  "snes-super-star-wars-usa",
  "snes-super-bomberman-2-usa",
  "snes-super-bomberman-usa",

  // Classicos cult / criticamente aclamados (nao venderam milhoes mas
  // aparecem quase sempre no topo das listas de "melhores de todos")
  "snes-earthbound-usa",
  "snes-terranigma-europe",
  "snes-super-castlevania-iv-usa",
  "snes-castlevania-dracula-x-usa",
  "snes-contra-iii-the-alien-wars-usa",
  "snes-teenage-mutant-ninja-turtles-iv-turtles-in-time-usa",
  "snes-super-punch-out-usa",
  "snes-actraiser-usa",
  "snes-actraiser-2-usa",
  "snes-kirby-s-dream-course-usa",
  "snes-kirby-s-avalanche-usa",
  "snes-international-superstar-soccer-usa",
  "snes-harvest-moon-usa",
  "snes-breath-of-fire-usa",
  "snes-breath-of-fire-ii-usa",
  "snes-illusion-of-gaia-usa",
  "snes-zombies-ate-my-neighbors-usa",
  "snes-pocky-rocky-usa",
  "snes-u-n-squadron-usa",
  "snes-gradius-iii-usa",
  "snes-axelay-usa",
  "snes-super-r-type-usa",
  "snes-uniracers-usa",
  "snes-rock-n-roll-racing-usa",
  "snes-battletoads-in-battlemaniacs-usa",
  "snes-ogre-battle-the-march-of-the-black-queen-usa",
  "snes-front-mission-japan",
  "snes-tales-of-phantasia-japan",
  "snes-star-ocean-japan",
  "snes-bahamut-lagoon-japan",

  // PS1 — mesmo criterio do SNES acima (best-sellers + classicos
  // aclamados), cruzado com o que realmente existe na pasta PS1/ do
  // usuario (a colecao dele nao tem Final Fantasy VII/VIII/IX nem o
  // Metal Gear Solid principal, so o spin-off VR Missions — por isso
  // nao aparecem aqui).
  "ps1-crash-bandicoot-1",
  "ps1-crash-bandicoot-2-cortex-strikes-back",
  "ps1-crash-bandicoot-3",
  "ps1-spyro-the-dragon-1",
  "ps1-spyro-the-dragon-2-riptos-rage",
  "ps1-spyro-the-dragon-3-year-of-the-dragon",
  "ps1-croc-legend-of-the-gobbos",
  "ps1-croc-2",
  "ps1-gex-2-enter-the-gecko",
  "ps1-klonoa-door-to-phantomile",
  "ps1-rayman",
  "ps1-ape-escape",
  "ps1-pac-man-world",
  "ps1-crash-team-racing",
  "ps1-final-fantasy-tactics",
  "ps1-final-fantasy-vi",
  "ps1-final-fantasy-chronicles-chrono-trigger",
  "ps1-vagrant-story",
  "ps1-suikoden",
  "ps1-suikoden-2",
  "ps1-legend-of-legaia",
  "ps1-wild-arms",
  "ps1-brave-fencer-musashi",
  "ps1-threads-of-fate",
  "ps1-legend-of-mana",
  "ps1-alundra-1",
  "ps1-front-mission-3",
  "ps1-persona-revelations-series",
  "ps1-shin-megami-tensei",
  "ps1-lunar-silver-star-story-complete-disc-1",
  "ps1-vandal-hearts",
  "ps1-brigandine-legend-of-forsena",
  "ps1-beyond-the-beyond",
  "ps1-azure-dreams",
  "ps1-tales-of-destiny",
  "ps1-resident-evil-usa",
  "ps1-resident-evil-director-s-cut",
  "ps1-resident-evil-2-dual-shock-ver-usa-disc-1-leon",
  "ps1-resident-evil-3-nemesis",
  "ps1-dino-crisis-1",
  "ps1-dino-crisis-2",
  "ps1-silent-hill",
  "ps1-parasite-eve",
  "ps1-tomb-raider-1",
  "ps1-tomb-raider-2-starring-lara-croft",
  "ps1-tomb-raider-3-adventures-of-lara-croft",
  "ps1-medievil",
  "ps1-medievil-2",
  "ps1-syphon-filter",
  "ps1-legacy-of-kain-soul-reaver",
  "ps1-blood-omen-legacy-of-kain",
  "ps1-oddworld-abe-s-oddysee",
  "ps1-tekken-1",
  "ps1-tekken-2",
  "ps1-tekken-3",
  "ps1-soul-blade",
  "ps1-bloody-roar-1",
  "ps1-bloody-roar-2-bringer-of-the-new-age",
  "ps1-street-fighter-alpha-3",
  "ps1-mortal-kombat-trilogy",
  "ps1-guilty-gear",
  "ps1-gran-turismo-1",
  "ps1-gran-turismo-2",
  "ps1-ridge-racer-type-4",
  "ps1-wipeout",
  "ps1-wipeout-xl",
  "ps1-need-for-speed-4-high-stakes",
  "ps1-colony-wars",
  "ps1-bomberman",
  "ps1-worms-armageddon",
  "ps1-point-blank",
]);
